version: 0.0
os: linux
files:
  - source: Dockerfile
    destination: /home
hooks:
  BeforeInstall:
    - location: scripts/clear.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/deploy_image.sh
      timeout: 3000
      runas: root
